function test00 = importVSP(filename)
%IMPORTVSP Import data from a text file
%  TEST00 = IMPORTVSP(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  Example:
%  test00 = IMPORTVSP("C:\Users\LBecce\OneDrive - Scientific Network South Tyrol\ProveN60\scripts\dati\test00.txt");
%
% Auto-generated by MATLAB and edited by Lorenzo Becce on 04-Feb-2022

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [10, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Frame", "ParticleID", "Diameter", "Velocity", "Angle", "ShapeFactor"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
test00 = readtable(filename, opts);

end

%%
% % just some stuff to plot distros
% cD01 = fitdist(test01.Diameter,'Lognormal')
% hold on
% plot(base,cD01.pdf(base))

% % this piece plots averages of subset of drops based on their shape
% % factor. This was developed to understand what the fuck
% I = 5;
% filtro = linspace(min(test00.ShapeFactor),max(test00.ShapeFactor),I);
% for j = 1:I
%     medie(j) = mean(test00.Diameter(test00.ShapeFactor >= filtro(j)));
% end
% plot(filtro,medie)